---
- name: Create directory
  file:
    path: /opt/monitoring/
    state: directory
    recurse: yes

- name: Template prerequirements.yml
  ansible.builtin.template:
    src: prerequirements.yml.j2
    dest: /opt/monitoring/prerequirements.yml

- name: Deploy prerequirements.yml
  become: true
  shell: |
    kubectl apply -f ./prerequirements.yml
  args:
    chdir: /opt/monitoring/
