---
- name: All in one playbook
  hosts: "{{ target | default('nas') }}"
  vars_files:
    - vars/docker.yml
    - vars/main.yml
    - vars/zfs.yml
  roles:
    - { role: apps }
    - { role: pyenv }
    - { role: lvm }
    - { role: docker }
    - { role: unattended-upgrades }
