- name: Install monitoring (prometheus)
  hosts: "{{ target | default('None') }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: tasks/02-prometheus.yml instead of 'main'
      ansible.builtin.include_role:
        name: monitoring
        tasks_from: 02-prometheus.yml
