- name: "Prepare {{ tmp_dir }} folder"
  ansible.builtin.file:
    state: directory
    path: "{{ tmp_dir }}"

- name: "Prepare user-data"
  ansible.builtin.template:
    src: user-data.yml.j2
    dest: "{{ tmp_dir }}/user-data"
