---
- include_tasks: 00-prerequirements.yml
- include_tasks: 01-k3s.yml

### haproxy-ingress
# TO BE REENABLED
# - name: Install Haproxy-ingress
#   shell: |
#     /home/linuxbrew/.linuxbrew/bin/helm repo add haproxy-ingress https://haproxy-ingress.github.io/charts
#     /home/linuxbrew/.linuxbrew/bin/helm repo update
#     /home/linuxbrew/.linuxbrew/bin/helm upgrade --install ingress haproxy-ingress/haproxy-ingress \
#       --create-namespace --namespace ingress-controller \
#       --set controller.stats.enabled=true \
#       --set controller.stats.port=30000 \
#       --set controller.daemonset.useHostPort=true

- include_tasks: 02-cert-manager.yml
- include_tasks: 03-longhorn.yml
