---
- name: Add Liquorix PPA
  become: true
  ansible.builtin.shell: |
    add-apt-repository ppa:damentz/liquorix && sudo apt-get update

- name: Install Liquorix Kernel
  become: true
  ansible.builtin.shell: |
    apt-get install linux-image-liquorix-amd64 linux-headers-liquorix-amd64
