---
- name: Ensure packages are installed
  become: true
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  loop:
    - tree
    - httpie
    - smartmontools
    - git
    - net-tools
